__author__ = 'slaven'

from django import forms
from .models import Basestations


class BasestationForm(forms.ModelForm):
    class Meta:
        model = Basestations

        fields = (
            'call_sign',
            'address',
            'netid',
            # 'type_coord',
            'coord_x',
            'coord_y',
            # altitude',
            'nominal_power',
            'gain',
            # 'gainrx',
            # 'losses',
            # 'lossesrx',
            # 'frequency',
            'h_antenna',
            # 'polar',
            # 'polarrx,'
            'threshold',
            # 'thresholdrx',
            'bandwidth',
            'bandwidthrx',
            # 'channel',
            # 'nb_lines',
            # 'title',
            # 'info1',
            # 'info2',
            'azimuth',
            'tilt',
            'tilte',
            # 'type_element',
            # 'info3',
            # 'type_station',
            # 'type_link',
            # 'group',
            'antenna_nameh',
            # 'antenna_namev',
            # 'diagh_0',
            # 'diagh_5',
            # 'diagh_10',
            # 'diagh_15',
            # 'diagh_20',
            # 'diagh_25',
            # 'diagh_30',
            # 'diagh_35',
            # 'diagh_40',
            # 'diagh_45',
            # 'diagh_50',
            # 'diagh_55',
            # 'diagh_60',
            # 'diagh_65',
            # 'diagh_70',
            # 'diagh_75',
            # 'diagh_80',
            # 'diagh_85',
            # 'diagh_90',
            # 'diagh_95',
            # 'diagh_100',
            # 'diagh_105',
            # 'diagh_110',
            # 'diagh_115',
            # 'diagh_120',
            # 'diagh_125',
            # 'diagh_130',
            # 'diagh_135',
            # 'diagh_140',
            # 'diagh_145',
            # 'diagh_150',
            # 'diagh_155',
            # 'diagh_160',
            # 'diagh_165',
            # 'diagh_170',
            # 'diagh_175',
            # 'diagh_180',
            # 'diagh_185',
            # 'diagh_190',
            # 'diagh_195',
            # 'diagh_200',
            # 'diagh_205',
            # 'diagh_210',
            # 'diagh_215',
            # 'diagh_220',
            # 'diagh_225',
            # 'diagh_230',
            # 'diagh_235',
            # 'diagh_240',
            # 'diagh_245',
            # 'diagh_250',
            # 'diagh_255',
            # 'diagh_260',
            # 'diagh_265',
            # 'diagh_270',
            # 'diagh_275',
            # 'diagh_280',
            # 'diagh_285',
            # 'diagh_290',
            # 'diagh_295',
            # 'diagh_300',
            # 'diagh_305',
            # 'diagh_310',
            # 'diagh_315',
            # 'diagh_320',
            # 'diagh_325',
            # 'diagh_330',
            # 'diagh_335',
            # 'diagh_340',
            # 'diagh_345',
            # 'diagh_350',
            # 'diagh_355',
            # 'project_owner',
            # 'project_name',
            # 'time_stamp',
            # 'status',
            # 'service',
            # 'codesitea',
            'downlink_cx',
            'd_cx1',
            'd_cx2',
            'd_cx3',
            'd_cx4',
            'd_cx5',
            'd_cx6',
            'd_cx7',
            'd_cx8',
            'd_cx9',
            'd_cx10',
            'd_cx11',
            'd_cx12',
            'd_cx13',
            'd_cx14',
            'd_cx15',
            'd_cx16',
            'uplink_cx',
            'u_cx1',
            'u_cx2',
            'u_cx3',
            'u_cx4',
            'u_cx5',
            'u_cx6',
            'u_cx7',
            'u_cx8',
            'u_cx9',
            'u_cx10',
            'u_cx11',
            'u_cx12',
            'u_cx13',
            'u_cx14',
            'u_cx15',
            'u_cx16',
            'spacing',
            'category',
            # 'wiencodeh',
            # 'wiencodev',
            # 'erlang',
            # 'call_no',
            # 'delay',
            # 'user',
            # 'til',
            # 'lineoffset',
            # 'precision',
            # 'dateserv',
            # 'datebegin',
            # 'dateend',
            'work_status',
            # 'rpe',
            # 'nfdname',
            # 'type_coord_adm',
            # 'coord_xadm',
            # 'coord_yadm',
            # 'coord_zadm',
            # 'sectorbegin',
            # 'sectorend',
            # 'distsimul',
            # 'modulation',
            # 'fktb',
            # 'aperture',
            # 'radius',
            # 'dynamic',
            # 'diameter',
            # 'xpd',
            # 'rad_step',
            # 'carrier',
            # 'thr10_3',
            # 'thr10_6',
            # 'noisefloor',
            # 'activity',
            # 'pilot',
            # 'paging',
            # 'sync',
            'bit_rate',
            # 'mchips_s',
            # 'discrep',
            # 'peak_pow',
            # 'pulse',
            # 'rd_noise',
            # 'det_pd',
            # 'channel_d',
            # 'plan',
            # 'ics_value',
            # 'heff_vi',
            # 'heff_ge',
            # 'diag_v',
            # 'icst_status',
            # 'polygon',
            # 'ant_fil',
            # 'options',
            'availability',
            # 'stringc',
            # 'addloss',
            'station_id',
            # 'color',
            # 'neighbours',
            'taclac',
            # 'rsi',
            # 'mme',
            # 'saegw',
            # 'pathcfd',
            # 'ci_n0',
            # 'ci_n1',
            # 'rdspi_sid',
            # 'lsn_swtpi',
            # 'tiimain',
            # 'tiisub',
            # 'fffh_trx',
            # 'etsi_class',
            # 'smart',
            # 'arraytx',
            # 'arrayrx',
            # 'mu',
            # 'pdcch',
            # 'pbch',
            # 'pss',
            # 'sss',
            'powermaxw',
            # 'change_date',
            # 'diag_h',
            # 'thr10_8',
            # 'thr10_10',
            # 'string',
            # 'chg_date',
            'pncode',
            'operator',
            'technology',
        )